# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-16 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seletable', models.CharField(help_text='选择表的名称', max_length=200, verbose_name='选择表的名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seletable', to=settings.AUTH_USER_MODEL, verbose_name='登陆账号名称')),
            ],
            options={
                'verbose_name': '归档目标表',
                'verbose_name_plural': '归档目标表',
            },
        ),
        migrations.AddField(
            model_name='taskmsg',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task', to=settings.AUTH_USER_MODEL, verbose_name='登陆账号名称'),
        ),
        migrations.AlterField(
            model_name='taskmsg',
            name='port',
            field=models.IntegerField(help_text='端口', verbose_name='端口'),
        ),
    ]
