# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-28 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200316_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmsg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 18, 4, 59, 12041), verbose_name='添加时间'),
        ),
    ]
