# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-29 15:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_taskmsg_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selefield', models.CharField(help_text='选择字段的名称', max_length=200, verbose_name='选择字段的名称')),
                ('rangetop', models.CharField(blank=True, help_text='过滤上限范围的名称', max_length=200, null=True, verbose_name='过滤上限范围的名称')),
                ('rangelow', models.CharField(blank=True, help_text='过滤下线范围的名称', max_length=200, null=True, verbose_name='过滤下线范围的名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selefield', to=settings.AUTH_USER_MODEL, verbose_name='登陆账号名称')),
            ],
            options={
                'verbose_name': '归档目标字段',
                'verbose_name_plural': '归档目标字段',
            },
        ),
        migrations.AlterField(
            model_name='taskmsg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 23, 40, 12, 771527), verbose_name='添加时间'),
        ),
    ]
