# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-31 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200329_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='selefield',
            name='taskid',
            field=models.IntegerField(default=0, help_text='任务id', verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='seletable',
            name='taskid',
            field=models.IntegerField(default=0, help_text='任务id', verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='taskmsg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 22, 41, 35, 938271), verbose_name='添加时间'),
        ),
    ]
