# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-31 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200331_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmsg',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskmsg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 15, 53, 465664), verbose_name='添加时间'),
        ),
    ]
